apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/layer: edge
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api-gateway
        app.kubernetes.io/layer: edge
        protocol: quantum
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: aetherflow-api-gateway
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: api-gateway
        image: aetherflow/api-gateway:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        - name: websocket
          containerPort: 8081
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: AETHERFLOW_ENV
          value: "production"
        - name: AETHERFLOW_LOG_LEVEL
          value: "info"
        - name: AETHERFLOW_HTTP_PORT
          value: "8080"
        - name: AETHERFLOW_HTTPS_PORT
          value: "8443"
        - name: AETHERFLOW_WEBSOCKET_PORT
          value: "8081"
        - name: AETHERFLOW_METRICS_PORT
          value: "9090"
        - name: ETCD_ENDPOINTS
          value: "etcd-service:2379"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-secret-key
        - name: QUANTUM_FEC_RATIO
          valueFrom:
            configMapKeyRef:
              name: quantum-protocol-config
              key: fec-ratio
        - name: QUANTUM_BBR_STARTUP_GAIN
          valueFrom:
            configMapKeyRef:
              name: quantum-protocol-config
              key: bbr-startup-gain
        - name: QUANTUM_MAX_CWND
          valueFrom:
            configMapKeyRef:
              name: quantum-protocol-config
              key: max-cwnd
        volumeMounts:
        - name: config
          mountPath: /etc/aetherflow
          readOnly: true
        - name: tls-certs
          mountPath: /etc/ssl/certs/aetherflow
          readOnly: true
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/startup
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      volumes:
      - name: config
        configMap:
          name: api-gateway-config
      - name: tls-certs
        secret:
          secretName: api-gateway-tls
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - api-gateway
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "aetherflow.io/edge-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
