apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app.kubernetes.io/component: etcd
    app.kubernetes.io/layer: coordination
spec:
  serviceName: etcd-headless
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: etcd
  template:
    metadata:
      labels:
        app.kubernetes.io/component: etcd
        app.kubernetes.io/layer: coordination
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2379"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: aetherflow-etcd
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.10
        imagePullPolicy: IfNotPresent
        ports:
        - name: client
          containerPort: 2379
          protocol: TCP
        - name: peer
          containerPort: 2380
          protocol: TCP
        env:
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_DATA_DIR
          value: /var/lib/etcd
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://$(ETCD_NAME).etcd-headless.$(POD_NAMESPACE).svc.cluster.local:2379
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: http://$(ETCD_NAME).etcd-headless.$(POD_NAMESPACE).svc.cluster.local:2380
        - name: ETCD_INITIAL_CLUSTER
          value: etcd-0=http://etcd-0.etcd-headless.$(POD_NAMESPACE).svc.cluster.local:2380,etcd-1=http://etcd-1.etcd-headless.$(POD_NAMESPACE).svc.cluster.local:2380,etcd-2=http://etcd-2.etcd-headless.$(POD_NAMESPACE).svc.cluster.local:2380
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: aetherflow-etcd-cluster
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ETCD_AUTO_COMPACTION_MODE
          value: periodic
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1h"
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "8589934592" # 8GB
        - name: ETCD_HEARTBEAT_INTERVAL
          value: "100"
        - name: ETCD_ELECTION_TIMEOUT
          value: "1000"
        - name: ETCD_MAX_SNAPSHOTS
          value: "5"
        - name: ETCD_MAX_WALS
          value: "5"
        - name: ETCD_SNAPSHOT_COUNT
          value: "100000"
        - name: ETCD_ENABLE_V2
          value: "false"
        - name: ETCD_LOG_LEVEL
          value: info
        - name: ETCD_LOGGER
          value: zap
        - name: ETCD_LOG_OUTPUTS
          value: stderr
        command:
        - /usr/local/bin/etcd
        volumeMounts:
        - name: etcd-data
          mountPath: /var/lib/etcd
        - name: etcd-config
          mountPath: /etc/etcd
          readOnly: true
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: client
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: client
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: client
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      volumes:
      - name: etcd-config
        configMap:
          name: etcd-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - etcd
            topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "aetherflow.io/etcd-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
      labels:
        app.kubernetes.io/component: etcd
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 50Gi
