// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/proto/statesync.proto

package statesync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StateSyncServiceClient is the client API for StateSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateSyncServiceClient interface {
	// 文档管理
	CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	// 操作管理
	ApplyOperation(ctx context.Context, in *ApplyOperationRequest, opts ...grpc.CallOption) (*ApplyOperationResponse, error)
	GetOperationHistory(ctx context.Context, in *GetOperationHistoryRequest, opts ...grpc.CallOption) (*GetOperationHistoryResponse, error)
	// 订阅管理
	SubscribeDocument(ctx context.Context, in *SubscribeDocumentRequest, opts ...grpc.CallOption) (StateSyncService_SubscribeDocumentClient, error)
	UnsubscribeDocument(ctx context.Context, in *UnsubscribeDocumentRequest, opts ...grpc.CallOption) (*UnsubscribeDocumentResponse, error)
	// 锁管理
	AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error)
	ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error)
	IsLocked(ctx context.Context, in *IsLockedRequest, opts ...grpc.CallOption) (*IsLockedResponse, error)
	// 统计信息
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type stateSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateSyncServiceClient(cc grpc.ClientConnInterface) StateSyncServiceClient {
	return &stateSyncServiceClient{cc}
}

func (c *stateSyncServiceClient) CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error) {
	out := new(CreateDocumentResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/CreateDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/GetDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error) {
	out := new(UpdateDocumentResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/UpdateDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/DeleteDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/ListDocuments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) ApplyOperation(ctx context.Context, in *ApplyOperationRequest, opts ...grpc.CallOption) (*ApplyOperationResponse, error) {
	out := new(ApplyOperationResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/ApplyOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) GetOperationHistory(ctx context.Context, in *GetOperationHistoryRequest, opts ...grpc.CallOption) (*GetOperationHistoryResponse, error) {
	out := new(GetOperationHistoryResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/GetOperationHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) SubscribeDocument(ctx context.Context, in *SubscribeDocumentRequest, opts ...grpc.CallOption) (StateSyncService_SubscribeDocumentClient, error) {
	stream, err := c.cc.NewStream(ctx, &StateSyncService_ServiceDesc.Streams[0], "/aetherflow.statesync.StateSyncService/SubscribeDocument", opts...)
	if err != nil {
		return nil, err
	}
	x := &stateSyncServiceSubscribeDocumentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StateSyncService_SubscribeDocumentClient interface {
	Recv() (*OperationEvent, error)
	grpc.ClientStream
}

type stateSyncServiceSubscribeDocumentClient struct {
	grpc.ClientStream
}

func (x *stateSyncServiceSubscribeDocumentClient) Recv() (*OperationEvent, error) {
	m := new(OperationEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stateSyncServiceClient) UnsubscribeDocument(ctx context.Context, in *UnsubscribeDocumentRequest, opts ...grpc.CallOption) (*UnsubscribeDocumentResponse, error) {
	out := new(UnsubscribeDocumentResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/UnsubscribeDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error) {
	out := new(AcquireLockResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/AcquireLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error) {
	out := new(ReleaseLockResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/ReleaseLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) IsLocked(ctx context.Context, in *IsLockedRequest, opts ...grpc.CallOption) (*IsLockedResponse, error) {
	out := new(IsLockedResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/IsLocked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateSyncServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/aetherflow.statesync.StateSyncService/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateSyncServiceServer is the server API for StateSyncService service.
// All implementations must embed UnimplementedStateSyncServiceServer
// for forward compatibility
type StateSyncServiceServer interface {
	// 文档管理
	CreateDocument(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	UpdateDocument(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	// 操作管理
	ApplyOperation(context.Context, *ApplyOperationRequest) (*ApplyOperationResponse, error)
	GetOperationHistory(context.Context, *GetOperationHistoryRequest) (*GetOperationHistoryResponse, error)
	// 订阅管理
	SubscribeDocument(*SubscribeDocumentRequest, StateSyncService_SubscribeDocumentServer) error
	UnsubscribeDocument(context.Context, *UnsubscribeDocumentRequest) (*UnsubscribeDocumentResponse, error)
	// 锁管理
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
	ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error)
	IsLocked(context.Context, *IsLockedRequest) (*IsLockedResponse, error)
	// 统计信息
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedStateSyncServiceServer()
}

// UnimplementedStateSyncServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStateSyncServiceServer struct {
}

func (UnimplementedStateSyncServiceServer) CreateDocument(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDocument not implemented")
}
func (UnimplementedStateSyncServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedStateSyncServiceServer) UpdateDocument(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocument not implemented")
}
func (UnimplementedStateSyncServiceServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedStateSyncServiceServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedStateSyncServiceServer) ApplyOperation(context.Context, *ApplyOperationRequest) (*ApplyOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyOperation not implemented")
}
func (UnimplementedStateSyncServiceServer) GetOperationHistory(context.Context, *GetOperationHistoryRequest) (*GetOperationHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperationHistory not implemented")
}
func (UnimplementedStateSyncServiceServer) SubscribeDocument(*SubscribeDocumentRequest, StateSyncService_SubscribeDocumentServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeDocument not implemented")
}
func (UnimplementedStateSyncServiceServer) UnsubscribeDocument(context.Context, *UnsubscribeDocumentRequest) (*UnsubscribeDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnsubscribeDocument not implemented")
}
func (UnimplementedStateSyncServiceServer) AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedStateSyncServiceServer) ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedStateSyncServiceServer) IsLocked(context.Context, *IsLockedRequest) (*IsLockedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsLocked not implemented")
}
func (UnimplementedStateSyncServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedStateSyncServiceServer) mustEmbedUnimplementedStateSyncServiceServer() {}

// UnsafeStateSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateSyncServiceServer will
// result in compilation errors.
type UnsafeStateSyncServiceServer interface {
	mustEmbedUnimplementedStateSyncServiceServer()
}

func RegisterStateSyncServiceServer(s grpc.ServiceRegistrar, srv StateSyncServiceServer) {
	s.RegisterService(&StateSyncService_ServiceDesc, srv)
}

func _StateSyncService_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/CreateDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).CreateDocument(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/GetDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_UpdateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).UpdateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/UpdateDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).UpdateDocument(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/DeleteDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/ListDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_ApplyOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).ApplyOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/ApplyOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).ApplyOperation(ctx, req.(*ApplyOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_GetOperationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).GetOperationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/GetOperationHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).GetOperationHistory(ctx, req.(*GetOperationHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_SubscribeDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeDocumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateSyncServiceServer).SubscribeDocument(m, &stateSyncServiceSubscribeDocumentServer{stream})
}

type StateSyncService_SubscribeDocumentServer interface {
	Send(*OperationEvent) error
	grpc.ServerStream
}

type stateSyncServiceSubscribeDocumentServer struct {
	grpc.ServerStream
}

func (x *stateSyncServiceSubscribeDocumentServer) Send(m *OperationEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _StateSyncService_UnsubscribeDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).UnsubscribeDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/UnsubscribeDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).UnsubscribeDocument(ctx, req.(*UnsubscribeDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/AcquireLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).AcquireLock(ctx, req.(*AcquireLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/ReleaseLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).ReleaseLock(ctx, req.(*ReleaseLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_IsLocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsLockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).IsLocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/IsLocked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).IsLocked(ctx, req.(*IsLockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateSyncService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateSyncServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aetherflow.statesync.StateSyncService/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateSyncServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateSyncService_ServiceDesc is the grpc.ServiceDesc for StateSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aetherflow.statesync.StateSyncService",
	HandlerType: (*StateSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDocument",
			Handler:    _StateSyncService_CreateDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _StateSyncService_GetDocument_Handler,
		},
		{
			MethodName: "UpdateDocument",
			Handler:    _StateSyncService_UpdateDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _StateSyncService_DeleteDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _StateSyncService_ListDocuments_Handler,
		},
		{
			MethodName: "ApplyOperation",
			Handler:    _StateSyncService_ApplyOperation_Handler,
		},
		{
			MethodName: "GetOperationHistory",
			Handler:    _StateSyncService_GetOperationHistory_Handler,
		},
		{
			MethodName: "UnsubscribeDocument",
			Handler:    _StateSyncService_UnsubscribeDocument_Handler,
		},
		{
			MethodName: "AcquireLock",
			Handler:    _StateSyncService_AcquireLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _StateSyncService_ReleaseLock_Handler,
		},
		{
			MethodName: "IsLocked",
			Handler:    _StateSyncService_IsLocked_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _StateSyncService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeDocument",
			Handler:       _StateSyncService_SubscribeDocument_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/statesync.proto",
}
